#+TITLE:   人生的智慧――叔本华
#+AUTHOR:  Ynjxsjmh
#+EMAIL:   ynjxsjmh@163.com
#+OPTIONS: toc:t

* 第一章 基本的划分
#+BEGIN_QUOTE
  我认为决定凡人命运的根本差别在于三项内容，他们是：
    1）人的自身：即在最广泛意义上属于人的个性的东西。 因此，它包括人的健康、力量、外貌、气质、道德品格、精神
    智力及其潜在发展。
    2）人所拥有的身外之物：亦即财产和其他占有物。
    3）人向其他人所显示的样子：这可以理解为：人在其他人眼中所呈现的样子，亦即人们对他的看法。他人的看法又可 分为名誉、地位和名声。
  人与人之间在第一项的差别是大自然确实下来的，由此可推断：这些差别比起第二、三项的差别对于造成人们的幸福抑 或不幸福会产生更加根本和彻底的影响――因为后两项内容的差别只是出自人为的划分。
#+END_QUOTE

我对于关于第一项的差别的影响的言论有如下个人看法：
我认为一个人的健康、力量、气质和精神品质等因素都可以通过一个人的后天训练来改变。比如：一个热爱运动的人和一个总是
宅在屋子里的人相比，我相信热爱运动的人看起来会更加自信，更加活泼阳光。这一点，从气质上就可以明显的看出来。由于经
常锻炼的原因，他的体格相比来说也会更加强壮。因此从健康角度来说，热爱运动的人发生疾病的隐患也会小于总是宅在屋子里
的人。更为重要的是，热爱运动的人很大程度上会在运动过程中交很多的朋友，这点无异于有助于培养其交流能力。因此，无论
是从哪一点来看的话，热爱运动的人第一点都会优于宅在屋子里的人。而在旁人看来，热爱运动的人往往会更具有亲和力或者说
服力，或者能更好的表达自己的看法。从这一点来说，运动是的的确确的改变了别人对某个特定的人的看法，也就是原文提到的
第三点。
总的来说，我是不太认同叔本华的=人与人之间在第一项的差别是大自然确实下来的=这个言论。我的观点是这个可以通过后天的努力来改变。

* 第二章 人的自身
#+BEGIN_QUOTE
谁经常笑，谁就是幸福的；谁经常哭，谁就是痛苦不幸的。
#+END_QUOTE

#+BEGIN_QUOTE
使我们快乐或者忧伤的事物，不是那些客观、真实的事物，而是我们对这些事物的理解和把握。这就是爱比克泰德所说的“扰乱人们的不是客观事情，而是人们对客观事情的见解”。
#+END_QUOTE

P24
#+BEGIN_QUOTE
头脑思维狭隘的人容易收到无聊的侵袭，其原因就是他们的智力纯粹服务于他们的意欲，是意欲的工具。如果诱发意欲的动因暂时没有出现，那么，意欲就休息了，智力也就放假了――因为智力和意欲不一样，它不会自动活动起来。这样，人身上所有力量可怕地迂滞静止，这也就是无聊。为了应付无聊，人们就为意欲找出一些琐碎、微小、随意和暂时的动因以图刺激意欲，和以此激活智力――因为智力的任务本来就是理解、把握动因。
#+END_QUOTE

P25
#+BEGIN_QUOTE
正如我已经说过的，闲暇就是每一个人的生命存在开出的花朵，或者毋宁说是果实。也只有闲暇使人得以把握、支配自身，而那些自身具备某些价值的人才可以称得上是幸福的。但对于大多数人来说，闲暇只会造就一个无用的家伙，无所事事，无聊烦闷，他的自身变成了他的包袱。
#+END_QUOTE

P26
#+BEGIN_QUOTE
亚里士多德无比正确的说过：幸福属于那些能够自得其乐的人。
#+END_QUOTE

P28
#+BEGIN_QUOTE
幸福源自于人的内在，被亚里士多德的真知灼见所引证（《伦理学》）。他说：每一快乐都是以人从事某种活动，或者应用人的某种能力作为前提；没有这一前提，快乐也就无从谈起，亚里士多德的教导――即人的幸福全在于无拘束地施展人的突出才能。
#+END_QUOTE

P29
#+BEGIN_QUOTE
三种快乐：
每个人都会有适合自己的一类快乐，这由他身上所突出具备的是哪一种能力而定。
- 第一类是为=机体新陈代谢能力=所带来的乐趣：这包括吃喝、消化、休息和睡觉。
- 第二类是发挥=肌肉力量=所带来的乐趣：这些包括步行、跳跃、击剑、骑马、舞蹈、狩猎和各种各样的体育游戏；甚至打斗和战争也包括在内。
- 第三类为施展感觉能力方面的乐趣：这些包括观察、思考、感觉、阅读、默想、写作、学习、发明、演奏音乐和思考哲学等。
#+END_QUOTE

P30
#+BEGIN_QUOTE
大众的生活把大众引向浑噩、呆滞，他们的思想和欲望无一不是指向维护他们的个人安逸的那些渺小事物，正因为这样，他们的生活也就迈向了形形色色的苦难。所以，一旦他们停止为这些目标操劳，并且不得不返回依赖他们的自身内在时，无法忍受的无聊就向他们袭来。这时候，只有情欲的疯狂火焰，才可以活动一下那呆滞和死气沉沉的众生生活。
#+END_QUOTE

P31
#+BEGIN_QUOTE
正如伏尔泰所正确无误地说过，“只要有真正的需求，才会有真正的快乐。”
#+END_QUOTE
这句对程序员来说是十分的真实了。

P32
#+BEGIN_QUOTE
“没有精神思想消遣的闲暇就是死亡，它就像要把人活生生地埋葬”（赛尼家语）
#+END_QUOTE

P33
#+BEGIN_QUOTE
常人却寄希望于身外之物，寄望于从财产、地位、妻子、儿女、朋友、社会人群那里获取生活快乐；他把自己一生的幸福寄托在这些上面。因此一旦他失去了这些东西，或者对这些东西的幻想破灭，那他的幸福也就随之烟消云散了。为了把这种情形表达清楚，我们可以这样说：这个人的重心在他的=自身之外=。
#+END_QUOTE

P34
#+BEGIN_QUOTE
亚里士多德在《政治学》里说过：能够不受阻碍地培养、发挥一个人的突出才能，不管这种才能是什么，是为真正的幸福。
#+END_QUOTE

P36
#+BEGIN_QUOTE
如果人们不能通过各种幻想的、虚假的目标，以各式游戏消遣和爱好来填塞时间，到最后，闲暇就会变成了痛苦。基于同样的原因，闲暇还会给人们带来危险，因为“当一个人无所事事的时候难以保持安静”是相当正确的。
#+END_QUOTE
这一点对于暑假中后期的学生来说体会应该比较深刻。

P38
#+BEGIN_QUOTE
没有真正的需求也就没有真正的快乐
#+END_QUOTE
软件开发工程师应该对这点有深刻的体会。

* 第三章 人所拥有的财产
关于可得和不可得的论述
P43
#+BEGIN_QUOTE
当对某一样东西的要求还没有进入一个人的意识的时候，这个人完全不会感觉到对它有所欠缺。没有这样东西，他照样心安理得。但一个拥有百倍以上财产的人，只要他对某样东西产生了要求，而又得不到它，那他就会怏怏不乐。在这一方面，对于一些他认为有可能得到满足的要求，每个人都有他的视线范围。他的要求不会超出这一视线范围。处于他心目中的视线范围之内的具体事物一旦出现，而他又确信能够得到它，那他就会感到幸福。但是如果得到这具体之物存在重重困难，他根本就没有得到它的希望和可能，那他就会感觉不幸和痛苦。所有在他视线以外的东西，都不会对他产生任何影响。因此穷人不会因为得不到巨大的财富而焦虑不安，但富人在计划失算落空的时候，不会考虑到自己已经拥有相当可观的财物，并以此安慰自己。
#+END_QUOTE

P44
#+BEGIN_QUOTE
我们之所以感到不满，原因就在于我们不断试图提高我们的要求，但同时，其他妨碍我们成功的条件因素却保持不变。
#+END_QUOTE

对于才能的看法：
P45
#+BEGIN_QUOTE
如果一个人凭借自己的某种天赋才能――不管这种才能是什么――从最初的一文不名到最终赚到可观的金钱，那么他就会错觉地认为：自己的天赋才能是永恒不变的本金，他以此赚取的金钱只是本金的利息而已。因此，他不会把挣来的一部分金钱积累成为固定长久的本金，而是把挣来的钱随手花掉。这样，他们通常最终陷入贫困，因为如果他们的才能只能维持短暂的时间，那么，他们的天赋才能就有枯竭、耗尽的时候。又或者，他们挣钱的本事依赖某种环境和某种风气。这种环境和风气随后消失了，这样，他们的钱财收入也就停止了。
#+END_QUOTE



* 第四章 人所展现的表象

下面的部分内容讲述了我们应该如何面对别人的称赞和贬低。
P51
#+BEGIN_QUOTE
我们所展现的表象――这也就是我们的存在在他人心目中的样子――通常被我们过分看重，这是我们人性的一个特殊弱点所致，虽然稍作简单的思考我们就可以知道，他人的看法就其本身来说，对我们的幸福并非至关重要。因此，很难解释清楚为什么每当一个人看见自己似乎留给他人一个好评语时，他的心里就高兴，他的虚荣心也就受到了某种安慰。
#+END_QUOTE

P51
#+BEGIN_QUOTE
当一个人受到他人的称赞时，愉悦之情就不可避免地洋溢于脸上。只要某种赞扬在一个人所期望的范围之内，那么，尽管他人的赞扬明显地虚伪不真，他仍然会高兴。
#+END_QUOTE

P51
#+BEGIN_QUOTE
令人惊讶的是，无论在何种情况下，如果他们想获得别人好评的雄心受到任何意义上和程度上的挫折，或者，当他们受到别人轻视、不敬、怠慢时，都肯定会难过、伤心，很多时候还会感受到深刻的创痛。
#+END_QUOTE

P54
#+BEGIN_QUOTE
几乎所有的人毕生不息地奋斗，历经千难万险，最终的目标就是让别人对自己刮目相看。
#+END_QUOTE

P54
#+BEGIN_QUOTE
在各种训练人的手法当中，加强和培养荣誉感的做法占据了首要的位置。但对于我们的幸福――这是我们的目的――荣誉感却是完全的另一码事。
#+END_QUOTE

P55
#+BEGIN_QUOTE
事实上，我们对他人的看法的注重，以及我们在这一方面的担忧，一般都超出了任何合理的程度，我们甚至可把这是为一种普遍流传的，或者更确切地说，是人类与生俱来的一种疯狂。我们无论要做或者不做什么事情，我们首要考虑的几乎就是别人的看法。
#+END_QUOTE

P57
#+BEGIN_QUOTE
很明显，要增进我们的幸福――它主要依赖我们平和与满足的心情――再没有比限制和减弱人的这种冲动更好的办法了。
#+END_QUOTE

P59
#+BEGIN_QUOTE
最廉价的骄傲就是民族的自豪感。沾染上民族自豪感的人暴露出这一事实：这个人缺乏个人的、他能够引以为豪的素质。
#+END_QUOTE

P61
#+BEGIN_QUOTE
客观上，名誉是他人对我们的价值的看法。
主管上，则是我们对他人看法的顾忌。
#+END_QUOTE
